### ISSUE TITLE
New versions of Forge are breaking many mods, including Simple Ore Generation

### ISSUE THREAD

**Issue by Zarepheth** [Rohzek/SimpleOreGeneration#12]
The newest versions of Forge, specifically those after 14.21.0.2348, are breaking many mods. Amongst the broken mods is Simple Ore Generation.

Minecraft 1.12
Forge 14.21.0.2359
Simple Ore Generation 4.0.0

```
[17:10:56] [main/FATAL] [FML]: The following problems were captured during this phase
[17:10:56] [main/ERROR] [FML]: Caught exception from simpleoregen (java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry)
```

```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Simple Ore Generation (simpleoregen)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:625)
	...
```

[Log File on paste.ee](https://paste.ee/p/qpXn5)

**Comment by Rohzek** [comment]
I'm going to assume, that it just means Forge changed something, and that rebuilding the mod on an updated version should fix the issue. I'll do that right now, and upload the jar to the Github to test. If it solves your problem, I'll upload the fix to curseforge. :)

**Comment by Zarepheth** [comment]
From another mod's author's comments, it seems that Forge has made a breaking change to one of their registry systems. Apparently, those paying attention to such things were aware of it in advance, although perhaps not the timing...

Anyway, I'll not be able to test this until Sunday afternoon or Evening.

**Comment by Rohzek** [comment]
I see. The only registry change I was aware of is the differences in crafting recipes. I'll guess I'll be figuring it out, though.

It's quite alright though, no rush. As long as Forge doesn't have a stable release, problems are expected to happen.

**Comment by Rohzek** [comment]
[Here's ](https://github.com/Rohzek/SimpleOreGeneration/tree/master/builds)a quick link to it. :)

**Comment by Zarepheth** [comment]
I gave it a try, still failing. But from what I'm experiencing and have seen with other mods, other people are trying to keep their mods current with Forge but also failing. Right now, it's hard to know which mods work with which version of Forge.

Minecraft: 1.12
Forge: 14.21.0.2367
Simple Ore Generation: [4.0.1](https://github.com/Rohzek/SimpleOreGeneration/blob/master/builds/SimpleOreGeneration-4.0.1%20mc%201.12.jar)

```
[19:48:01] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.ModelRegistryEvent@6f211822:
java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/RegistryDelegate
	at net.minecraft.client.renderer.block.model.ModelBakery.registerItemVariants(ModelBakery.java:1081) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.setCustomModelResourceLocation(ModelLoader.java:1142) ~[ModelLoader.class:?]
	at com.gmail.rohzek.blocks.SGOres.registerRender(SGOres.java:157) ~[SGOres.class:?]
	at com.gmail.rohzek.blocks.SGOres.registerRenders(SGOres.java:93) ~[SGOres.class:?]
	at com.gmail.rohzek.events.LoadModelsEvent.onModelRegistry(LoadModelsEvent.java:17) ~[LoadModelsEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_36_LoadModelsEvent_onModelRegistry_ModelRegistryEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
```

[Log File on paste.ee](https://paste.ee/p/AgykD)

**Comment by Rohzek** [comment]
Should hopefully be fixed in the latest versions, now that Forge has a stable, recommended release.

**Comment by Zarepheth** [comment]
It's now working, but I had to follow the advice on about deleting the OreGen.json file to clear the startup errors.
And doing a comparison between the old and new OreGen.json, it looks like you're now handling more ores, and improving the mining level.

**Comment by Rohzek** [comment]
Glad everything's working now. :)
